CREATE TABLE grand_competitions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  title VARCHAR(250) NOT NULL UNIQUE,
  hashtag VARCHAR(20) NOT NULL UNIQUE,
  competition_start DATE NOT NULL,
  competition_end DATE NOT NULL,
  status VARCHAR(20) NOT NULL,
  location VARCHAR(250) NOT NULL,
  description VARCHAR(1000) NOT NULL
);

CREATE TABLE grand_competition_fields (
  grand_competition_id BIGINT NOT NULL REFERENCES grand_competitions(id) ON DELETE CASCADE,
  field VARCHAR(20) NOT NULL,
  PRIMARY KEY (grand_competition_id, field)
);